# Generated by Django 2.1.5 on 2019-07-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('lyrics', models.TextField()),
                ('composer', models.CharField(max_length=100)),
                ('featuring', models.TextField(blank=True)),
                ('album', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='')),
                ('link', models.CharField(max_length=1000)),
                ('ytlink', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
