# Generated by Django 2.1.5 on 2019-06-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='ytlink',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
