# Generated by Django 2.1.5 on 2019-08-09 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_song_ytlink'),
        ('songs', '0003_auto_20190730_1744'),
    ]

    operations = [
    ]
